version: '3.1'
services:
  web:
    build: web/
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - TYPO3_INSTALL_DB_DBNAME=${TYPO3_INSTALL_DB_DBNAME}
      - TYPO3_INSTALL_DB_USE_EXISTING=${TYPO3_INSTALL_DB_USE_EXISTING}
      - TYPO3_INSTALL_DB_USER=${TYPO3_INSTALL_DB_USER}
      - TYPO3_INSTALL_DB_PASSWORD=${TYPO3_INSTALL_DB_PASSWORD}
      - TYPO3_INSTALL_DB_HOST=${TYPO3_INSTALL_DB_HOST}
      - TYPO3_INSTALL_DB_PORT=${TYPO3_INSTALL_DB_PORT}
      - TYPO3_INSTALL_ADMIN_USER=${TYPO3_INSTALL_ADMIN_USER}
      - TYPO3_INSTALL_ADMIN_PASSWORD=${TYPO3_INSTALL_ADMIN_PASSWORD}
      - TYPO3_INSTALL_SITE_NAME=${TYPO3_INSTALL_SITE_NAME}
      - TYPO3_INSTALL_SITE_SETUP_TYPE=${TYPO3_INSTALL_SITE_SETUP_TYPE}
      - TYPO3_INSTALL_WEB_SERVER_CONFIG=${TYPO3_INSTALL_WEB_SERVER_CONFIG}
    tmpfs:
      - /var/www/html/typo3/var:size=256M

  db:
    build: mariadb/
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${TYPO3_INSTALL_DB_USER}
      - MYSQL_PASSWORD=${TYPO3_INSTALL_DB_PASSWORD}
      - MYSQL_DATABASE=${TYPO3_INSTALL_DB_DBNAME}
    healthcheck:
      test: "mysqladmin -uroot -p${MYSQL_ROOT_PASSWORD} -hlocalhost ping"
      interval: 10s
      timeout: 20s
      retries: 10

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8036:8080

